import { DM_Sans } from "next/font/google";
import type { Metadata } from "next";
import { ThemeProvider } from "@/lib/providers/next-theme-provider";
import "./globals.css";
import { twMerge } from "tailwind-merge";

const dm_sans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={twMerge(dm_sans.className, "bg-background")}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
